'use client';
import { useState, useEffect } from 'react';

export default function SystemLogs() {
  const [logs, setLogs] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  const fetchLogs = async () => {
    try {
      const res = await fetch('/api/logs');
      if (res.ok) {
        const data = await res.json();
        setLogs(data);
      }
    } catch (error) {
      console.error("Error fetching logs:", error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchLogs();
    // Optional: Refresh logs every 30 seconds for live monitoring
    const interval = setInterval(fetchLogs, 30000);
    return () => clearInterval(interval);
  }, []);

  // Helper to style the action badges
  const getActionBadge = (action) => {
    switch (action) {
      case 'SECURE_LOGIN':
        return <span className="bg-[#E5F6E5] text-[#006600] border border-[#008000] px-2 py-1 text-[10px] font-bold tracking-wider">SECURE LOGIN</span>;
      case 'SECURE_LOGOUT':
        return <span className="bg-[#F8F9FA] text-[#555555] border border-[#CCCCCC] px-2 py-1 text-[10px] font-bold tracking-wider">SESSION TERMINATED</span>;
      case 'FAILED_LOGIN_ATTEMPT':
        return <span className="bg-[#FFEEEE] text-[#CC0000] border border-[#CC0000] px-2 py-1 text-[10px] font-bold tracking-wider animate-pulse">FAILED ATTEMPT</span>;
      default:
        return <span className="bg-[#E6F0FA] text-[#003366] border border-[#003366] px-2 py-1 text-[10px] font-bold tracking-wider">{action}</span>;
    }
  };

  return (
    <div className="w-full text-[#333333] font-sans pb-10">
      
      {/* Official Page Header */}
      <div className="border-b-2 border-[#003366] pb-2 mb-6">
        <h1 className="text-xl md:text-2xl font-bold text-[#003366] uppercase m-0 tracking-wide">
          System Audit Logs
        </h1>
        <p className="text-xs text-[#555555] font-bold uppercase mt-1">IEDC Portal • Security & Access Monitoring</p>
      </div>

      {/* Security Notice */}
      <div className="bg-[#FFF4E5] border border-orange-400 p-3 mb-6 flex items-start gap-3">
        <div className="bg-orange-500 text-white px-2 py-0.5 text-[10px] font-bold mt-0.5">RESTRICTED</div>
        <p className="text-xs text-[#555555] font-bold uppercase tracking-wide leading-relaxed m-0">
          This log contains sensitive authentication data. Review access patterns regularly to ensure portal integrity. 
          Records are immutable and generated by the server.
        </p>
      </div>
      
      {/* Directory Table for Logs */}
      <div className="border border-[#CCCCCC] shadow-sm overflow-x-auto bg-white">
        <div className="bg-[#E5E7EB] border-b border-[#CCCCCC] px-4 py-3 text-sm font-bold text-[#003366] uppercase flex justify-between items-center">
          <span>Official Authentication Ledger</span>
          <span className="text-xs bg-white border border-[#CCCCCC] px-2 py-0.5 text-[#555555]">
            Total Entries: {logs.length}
          </span>
        </div>
        
        <table className="w-full text-left border-collapse min-w-[700px]">
          <thead className="bg-[#F8F9FA] border-b-2 border-[#CCCCCC]">
            <tr>
              <th className="p-3 text-xs font-bold text-[#555555] border-r border-[#CCCCCC] w-20 text-center">LOG ID</th>
              <th className="p-3 text-xs font-bold text-[#555555] border-r border-[#CCCCCC] w-48">TIMESTAMP (IST)</th>
              <th className="p-3 text-xs font-bold text-[#555555] border-r border-[#CCCCCC]">USER IDENTITY</th>
              <th className="p-3 text-xs font-bold text-[#555555] w-48 text-center">AUDIT EVENT</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#CCCCCC]">
            {isLoading ? (
              <tr>
                <td colSpan="4" className="p-6 text-center text-sm font-bold text-[#003366] bg-[#F8F9FA] animate-pulse uppercase">
                  FETCHING SECURE LOGS...
                </td>
              </tr>
            ) : logs.length > 0 ? (
              logs.map((log) => (
                <tr key={log.id} className="hover:bg-[#F0F5FA] transition-none">
                  <td className="p-3 text-[11px] font-mono font-bold text-[#777777] border-r border-[#CCCCCC] text-center align-middle">
                    #{String(log.id).padStart(5, '0')}
                  </td>
                  <td className="p-3 text-xs font-bold text-[#333333] border-r border-[#CCCCCC] align-middle">
                    {new Date(log.created_at).toLocaleString('en-IN', { 
                      day: '2-digit', month: 'short', year: 'numeric', 
                      hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true 
                    }).toUpperCase()}
                  </td>
                  <td className="p-3 border-r border-[#CCCCCC] align-middle">
                    <div className="font-bold text-sm text-[#003366]">{log.user_email}</div>
                  </td>
                  <td className="p-3 text-center align-middle">
                    {getActionBadge(log.action)}
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan="4" className="p-6 text-center text-sm text-[#777777] italic bg-[#F8F9FA]">
                  No authentication records found in the database.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

    </div>
  );
}
