'use client';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import { motion } from 'framer-motion';
export default function AboutIEDC() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => { const controller = new AbortController(); (async () => { try { const res = await fetch('/api/about', { signal: controller.signal }); if (res.ok) setData(await res.json()); } catch (e) { if (e.name !== 'AbortError') console.error('Unable to load about content', e); } finally { if (!controller.signal.aborted) setLoading(false); } })(); return () => controller.abort(); }, []);
  const vision = data?.vision || 'A campus culture where students feel empowered to question, experiment, collaborate, and turn promising ideas into meaningful outcomes.';
  const objectives = Array.isArray(data?.objectives) ? data.objectives : ['Encourage creative problem-solving and interdisciplinary collaboration.', 'Connect students with mentors, startup resources, and practical learning.', 'Build confidence through workshops, projects, and community-led initiatives.'];
  return <section id="about" className="section section--dark about-section"><div className="about-glow" aria-hidden="true" /><div className="section-shell about-shell">
    <motion.div className="about-copy" initial={{ opacity: 0, x: -24 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .7 }}><p className="eyebrow eyebrow--light"><span className="eyebrow-number">02</span> A little about us</p><h2>Not just ideas.<br /><span className="hero-gradient">A launchpad.</span></h2><p className="about-lead">{data?.about_text || 'IEDC GPC Pala is a student-focused space for innovation, entrepreneurship, and technology. We help turn curiosity into projects, skills, and possibilities.'}</p><a href="#contact" className="button button--primary">Meet the community <span>↗</span></a></motion.div>
    <motion.div className="about-visual" initial={{ opacity: 0, scale: .97 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .8 }}><div className="about-photo about-campus-scene" aria-label="Government Polytechnic College Pala illustration with gently animated clouds, sun and grass"><div className="campus-sky" aria-hidden="true"><span className="campus-sun" /><span className="campus-cloud campus-cloud--one" /><span className="campus-cloud campus-cloud--two" /><span className="campus-cloud campus-cloud--three" /><span className="campus-coordinates">GPC PALA <i>•</i> KERALA, INDIA</span><span className="campus-crosshair">+</span></div><div className="campus-trees" aria-hidden="true"><svg className="campus-tree campus-tree--left" viewBox="0 0 180 300" preserveAspectRatio="xMidYMax meet"><path className="tree-trunk" d="M25 300 C42 230 44 156 60 80 L77 80 C66 157 68 229 86 300 Z"/><path className="tree-branch" d="M61 153 L25 108 M67 125 L100 85 M48 207 L16 176 M72 185 L113 143"/><g className="tree-canopy"><ellipse cx="49" cy="70" rx="43" ry="34"/><ellipse cx="92" cy="62" rx="48" ry="37"/><ellipse cx="123" cy="91" rx="43" ry="35"/><ellipse cx="52" cy="112" rx="48" ry="35"/><ellipse cx="95" cy="112" rx="50" ry="38"/><ellipse cx="25" cy="91" rx="28" ry="32"/><ellipse cx="135" cy="57" rx="25" ry="26"/></g></svg><svg className="campus-tree campus-tree--right" viewBox="0 0 180 300" preserveAspectRatio="xMidYMax meet"><path className="tree-trunk" d="M105 300 C91 230 105 155 113 82 L130 82 C122 165 122 235 142 300 Z"/><path className="tree-branch" d="M113 155 L76 112 M119 126 L151 91 M119 208 L78 174 M128 181 L163 146"/><g className="tree-canopy"><ellipse cx="104" cy="68" rx="43" ry="34"/><ellipse cx="65" cy="61" rx="45" ry="36"/><ellipse cx="34" cy="90" rx="34" ry="32"/><ellipse cx="98" cy="111" rx="48" ry="38"/><ellipse cx="54" cy="111" rx="43" ry="34"/><ellipse cx="145" cy="91" rx="28" ry="31"/><ellipse cx="47" cy="54" rx="25" ry="27"/></g></svg></div><Image src="/gpc-building-illustration.png" alt="Government Polytechnic College, Pala campus illustration" fill sizes="(max-width: 800px) 100vw, 45vw" className="campus-building-art" /><div className="campus-grass" aria-hidden="true">{Array.from({ length: 21 }, (_, i) => <span key={i} className="campus-grass-blade" style={{ left: `${i * 4.8}%`, animationDelay: `${(i % 7) * -0.27}s`, height: `${8 + ((i * 7) % 12)}px` }} />)}</div><span className="campus-scene-edge" aria-hidden="true" /></div><div className="about-photo-caption"><span>CURIOUS BY NATURE</span><span>BUILT TO EXPLORE ↗</span></div></motion.div>
    <div className="about-bottom"><div className="about-info-block"><p className="eyebrow eyebrow--light">Our vision</p><p>{vision}</p></div><div className="about-info-block"><p className="eyebrow eyebrow--light">What we work toward</p><ul>{objectives.map((item, i) => <li key={`${i}-${item}`}><span>0{i + 1}</span>{item}</li>)}</ul></div></div>
    {loading && <span className="sr-only">Loading additional about content</span>}
  </div></section>;
}
