'use client';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import { motion } from 'framer-motion';
export default function Achievements() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const controller = new AbortController(); (async () => { try { const res = await fetch('/api/achievements', { signal: controller.signal }); if (res.ok) setItems(await res.json()); } catch (e) { if (e.name !== 'AbortError') console.error('Unable to load achievements', e); } finally { if (!controller.signal.aborted) setLoading(false); } })(); return () => controller.abort(); }, []);
  if (!loading && !items.length) return null;
  return <section id="achievements" className="section section--dark achievements-section"><div className="section-shell"><div className="section-heading section-heading--split"><div><p className="eyebrow eyebrow--light"><span className="eyebrow-number">05</span> Proof of possibility</p><h2>Progress worth<br /><span className="hero-gradient">celebrating.</span></h2></div><p className="section-intro section-intro--light">Every milestone begins with someone willing to try. Here’s a look at the progress our community has made.</p></div><div className="achievement-grid">{items.map((item, i) => <motion.article className={`achievement-card achievement-card--${i % 3}`} key={item.id} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ duration: .6, delay: i * .08 }}><div className="achievement-image">{item.image_url ? <Image src={item.image_url} alt={item.title || 'IEDC achievement'} fill sizes="(max-width: 700px) 100vw, 50vw" className="cover-image" /> : <div className="achievement-placeholder">✳</div>}<span className="achievement-number">0{i + 1}</span></div><div className="achievement-copy"><h3>{item.title}</h3><p>{item.description}</p></div></motion.article>)}</div>{loading && <div className="loading-line loading-line--light"><span /> Loading milestones…</div>}</div></section>;
}
