'use client';
import { useState } from 'react';
import { motion } from 'framer-motion';
export default function Contact() {
  const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [status, setStatus] = useState({ type: '', text: '' });
  async function handleSubmit(e) { e.preventDefault(); setBusy(true); setStatus({ type: '', text: '' }); try { const res = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: `${firstName} ${lastName}`.trim(), email, message }) }); if (!res.ok) throw new Error('Request failed'); setStatus({ type: 'success', text: 'Thanks for reaching out. Your message has been sent.' }); setFirstName(''); setLastName(''); setEmail(''); setMessage(''); } catch { setStatus({ type: 'error', text: 'We couldn’t send your message. Please try again in a moment.' }); } finally { setBusy(false); } }
  return <section id="contact" className="section section--dark contact-section"><div className="contact-glow" aria-hidden="true" /><div className="section-shell contact-layout"><motion.div className="contact-copy" initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .6 }}><p className="eyebrow eyebrow--light"><span className="eyebrow-number">08</span> Start a conversation</p><h2>Have a spark?<br /><span className="hero-gradient">Let’s build.</span></h2><p className="contact-lead">Have an idea, want to collaborate, or just curious about what we do? We’d love to hear from you.</p><div className="contact-details"><div><span>FIND US</span><p>Government Polytechnic College<br />Kanattupara, Pala P.O, Kottayam – 686575</p></div><div><span>WRITE TO US</span><a href="mailto:iedc.gpcpala@gmail.com">iedc.gpcpala@gmail.com ↗</a></div><div><span>CALL</span><a href="tel:04822200802">0482-2200802 ↗</a></div></div></motion.div>
    <motion.div className="contact-form-wrap" initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .65, delay: .1 }}><div className="form-heading"><span>YOUR TURN</span><span>LET’S TALK ↗</span></div><form onSubmit={handleSubmit} className="contact-form"><div className="form-row"><label>First name<input required autoComplete="given-name" value={firstName} onChange={e => setFirstName(e.target.value)} placeholder="Your First Name" /></label><label>Last name<input required autoComplete="family-name" value={lastName} onChange={e => setLastName(e.target.value)} placeholder="Your Last Name" /></label></div><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>What’s on your mind?<textarea required rows={4} value={message} onChange={e => setMessage(e.target.value)} placeholder="Tell us a little about it…" /></label>{status.text && <p className={`form-status form-status--${status.type}`} role="status">{status.text}</p>}<button type="submit" className="button button--primary form-submit" disabled={busy}>{busy ? 'Sending…' : 'Send your message'} <span>↗</span></button><p className="form-footnote">Your message goes directly to the IEDC team.</p></form></motion.div></div></section>;
}
