'use client';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { motion } from 'framer-motion';
export default function Events() {
  const [events, setEvents] = useState([]); const [loading, setLoading] = useState(true); const rail = useRef(null);
  useEffect(() => { const controller = new AbortController(); (async () => { try { const res = await fetch('/api/events', { signal: controller.signal }); if (res.ok) setEvents(await res.json()); } catch (e) { if (e.name !== 'AbortError') console.error('Unable to load events', e); } finally { if (!controller.signal.aborted) setLoading(false); } })(); return () => controller.abort(); }, []);
  const date = value => { const d = new Date(value); return Number.isNaN(d.getTime()) ? 'Date to be announced' : d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }); };
  return <section id="events" className="section section--light events-section"><div className="section-shell"><div className="section-heading section-heading--split"><div><p className="eyebrow"><span className="eyebrow-number">03</span> Make it happen</p><h2>Good things are<br /><span className="text-gradient">in the making.</span></h2></div><div className="events-heading-side"><p className="section-intro">Meet, make, compete, and learn. Find your next reason to get involved.</p><div className="rail-controls"><button type="button" aria-label="Scroll events left" onClick={() => rail.current?.scrollBy({ left: -420, behavior: 'smooth' })}>←</button><button type="button" aria-label="Scroll events right" onClick={() => rail.current?.scrollBy({ left: 420, behavior: 'smooth' })}>→</button></div></div></div>
    <div className="event-rail" ref={rail}>{events.map((event, i) => <motion.article className="event-card" key={event.id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ duration: .5, delay: i * .07 }}><div className="event-image">{event.image_url ? <Image src={event.image_url} alt={event.title || 'IEDC event'} fill sizes="(max-width: 700px) 82vw, 38vw" className="cover-image" /> : <div className="event-image-fallback"><span>IEDC / EVENTS</span><b>✳</b></div>}<span className="event-index">EVENT / {String(i + 1).padStart(2, '0')}</span></div><div className="event-details"><p className="event-date">{date(event.event_date)}</p><h3>{event.title}</h3><p className="event-description">{event.description}</p>{event.links?.length > 0 && <div className="event-links">{event.links.map((link, j) => <Link key={`${link.url}-${j}`} href={link.url} target="_blank" rel="noopener noreferrer" className="text-link">{link.label || 'Learn more'} <span>↗</span></Link>)}</div>}</div></motion.article>)}{!loading && events.length === 0 && <div className="empty-state"><span className="empty-state-icon">✳</span><h3>Something is in the works.</h3><p>No upcoming events are listed right now. Check back soon for what’s next.</p></div>}</div>{loading && <div className="loading-line"><span /> Loading upcoming events…</div>}</div></section>;
}
