'use client';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import { AnimatePresence, motion } from 'framer-motion';
export default function Gallery() {
  const [photos, setPhotos] = useState([]); const [loading, setLoading] = useState(true); const [active, setActive] = useState(null);
  useEffect(() => { const controller = new AbortController(); (async () => { try { const res = await fetch('/api/gallery', { signal: controller.signal }); if (res.ok) setPhotos(await res.json()); } catch (e) { if (e.name !== 'AbortError') console.error('Unable to load gallery', e); } finally { if (!controller.signal.aborted) setLoading(false); } })(); return () => controller.abort(); }, []);
  useEffect(() => { if (!active) return; const onKey = e => { if (e.key === 'Escape') setActive(null); }; window.addEventListener('keydown', onKey); document.body.style.overflow = 'hidden'; return () => { window.removeEventListener('keydown', onKey); document.body.style.overflow = ''; }; }, [active]);
  if (!loading && !photos.length) return null;
  return <section id="gallery" className="section section--light gallery-section"><div className="section-shell"><div className="section-heading section-heading--split"><div><p className="eyebrow"><span className="eyebrow-number">06</span> The moments between</p><h2>Life at <span className="text-gradient">IEDC.</span></h2></div><p className="section-intro">The people, experiments, late ideas, and little wins that make this community what it is.</p></div><div className="gallery-grid">{photos.map((photo, i) => <motion.button type="button" key={photo.id} className={`gallery-tile gallery-tile--${i % 5}`} onClick={() => setActive(photo)} aria-label={`View gallery photo ${i + 1}`} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .1 }} transition={{ duration: .5, delay: (i % 5) * .05 }}><Image src={photo.image_url} alt={photo.title || `IEDC community moment ${i + 1}`} fill sizes="(max-width: 700px) 50vw, 33vw" className="cover-image" /><span className="gallery-hover">View image ↗</span><span className="gallery-index">FRAME / {String(i + 1).padStart(2, '0')}</span></motion.button>)}</div>{loading && <div className="loading-line"><span /> Loading the gallery…</div>}</div><AnimatePresence>{active && <motion.div className="lightbox" role="dialog" aria-modal="true" aria-label="Gallery image viewer" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setActive(null)}><button className="lightbox-close" onClick={() => setActive(null)} aria-label="Close image viewer">×</button><motion.div className="lightbox-image" initial={{ scale: .96 }} animate={{ scale: 1 }} exit={{ scale: .96 }} onClick={e => e.stopPropagation()}><Image src={active.image_url} alt={active.title || 'IEDC gallery image'} fill sizes="90vw" className="cover-image" /></motion.div></motion.div>}</AnimatePresence></section>;
}
